/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
import MarkovProcess.Semigroup.PoissonInvariant
import MarkovProcess.Kernel.PositiveC0SemigroupFeller

/-!
# Positive `C₀` resolvents and their Feller kernels

A positive contractive resolvent on `C₀` canonically generates a strongly continuous semigroup
of positive contractions.  The existing pointwise Riesz construction then represents that
semigroup by a sub-Markov kernel semigroup and identifies its `C₀` operators exactly.

The package in this file starts from the resolvent identity, the Hille--Yosida bound, dense range,
and positivity of the actual shifted resolvents.  It assumes neither a semigroup nor a kernel.
-/

open MeasureTheory ProbabilityTheory Set
open scoped ZeroAtInfty

noncomputable section

namespace MarkovProcess

open MarkovProcess.Semigroup

variable (X : Type*) [TopologicalSpace X]

/-- A contractive resolvent on `C₀(X, ℝ)` whose shifted operators preserve nonnegative
functions. -/
structure PositiveC0ContractiveResolvent extends ContractiveResolvent C₀(X, ℝ) where
  /-- Every shifted resolvent is positivity preserving. -/
  isPositive : ∀ alpha,
    PositiveC0OperatorMeasure.IsPositive (toContractiveResolvent.operator alpha)

namespace PositiveC0ContractiveResolvent

variable {X : Type*} [TopologicalSpace X]

/-- The closed cone of pointwise nonnegative functions in `C₀(X, ℝ)`. -/
def nonnegativeSet : Set C₀(X, ℝ) :=
  {f | ∀ x, 0 ≤ f x}

theorem isClosed_nonnegativeSet : IsClosed (nonnegativeSet (X := X)) := by
  unfold nonnegativeSet
  rw [show {f : C₀(X, ℝ) | ∀ x, 0 ≤ f x} =
      ⋂ x : X, {f : C₀(X, ℝ) | f x ∈ Set.Ici 0} by
    ext f
    simp only [mem_setOf_eq, mem_iInter, mem_Ici]]
  apply isClosed_iInter
  intro x
  exact isClosed_Ici.preimage
    (((ZeroAtInftyContinuousMap.isometry_toBCF (α := X) (β := ℝ)).continuous).eval
      continuous_const)

theorem convex_nonnegativeSet : Convex ℝ (nonnegativeSet (X := X)) := by
  intro f hf g hg a b ha hb _hab x
  change 0 ≤ a * f x + b * g x
  exact add_nonneg (mul_nonneg ha (hf x)) (mul_nonneg hb (hg x))

theorem zero_mem_nonnegativeSet :
    (0 : C₀(X, ℝ)) ∈ nonnegativeSet (X := X) := by
  intro x
  exact le_rfl

variable (R : PositiveC0ContractiveResolvent X)

/-- Every normalized shifted resolvent preserves the pointwise nonnegative cone. -/
theorem preservesSet_scaledOperator_nonnegative (alpha : PositiveShift) :
    PreservesSet (R.toContractiveResolvent.scaledOperator alpha)
      (nonnegativeSet (X := X)) (nonnegativeSet (X := X)) := by
  intro f hf x
  change 0 ≤ (alpha : ℝ) * R.toContractiveResolvent.operator alpha f x
  exact mul_nonneg alpha.property.le (R.isPositive alpha f hf x)

/-- The canonical semigroup generated by a positive `C₀` contractive resolvent is positivity
preserving at every time. -/
theorem isPositive_generatedSemigroup :
    ∀ t, PositiveC0OperatorMeasure.IsPositive
      (R.toContractiveResolvent.generatedSemigroup t) := by
  intro t f hf
  exact R.toContractiveResolvent.preservesSet_generatedSemigroup_of_scaledOperator
    (nonnegativeSet (X := X)) isClosed_nonnegativeSet convex_nonnegativeSet
    zero_mem_nonnegativeSet R.preservesSet_scaledOperator_nonnegative t hf

section Kernel

variable [T2Space X] [LocallyCompactSpace X] [SecondCountableTopology X]
  [MeasurableSpace X] [BorelSpace X]

/-- The sub-Markov kernel semigroup represented by the canonical positive `C₀` semigroup. -/
noncomputable def kernelSemigroup : SubMarkovKernelSemigroup X :=
  PositiveC0SemigroupKernel.kernelSemigroup
    R.toContractiveResolvent.generatedSemigroup R.isPositive_generatedSemigroup

/-- The represented kernels act on `C₀` exactly by the generated semigroup operators. -/
theorem integral_kernelSemigroup (t : NNReal) (f : C₀(X, ℝ)) (x : X) :
    ∫ y, f y ∂R.kernelSemigroup t x =
      R.toContractiveResolvent.generatedSemigroup t f x := by
  rw [kernelSemigroup, PositiveC0SemigroupKernel.kernelSemigroup_apply]
  exact PositiveC0OperatorKernel.integral_kernel
    (R.toContractiveResolvent.generatedSemigroup t)
    (R.isPositive_generatedSemigroup t)
    (R.toContractiveResolvent.generatedSemigroup.norm_operator_le_one t) x f

/-- The represented kernel semigroup satisfies the Feller interface. -/
theorem isFellerKernelSemigroup_kernelSemigroup : R.kernelSemigroup.IsFellerKernelSemigroup :=
  PositiveC0SemigroupFeller.isFellerKernelSemigroup_kernelSemigroup
    R.toContractiveResolvent.generatedSemigroup R.isPositive_generatedSemigroup

/-- Repackaging the represented Feller kernels recovers the generated `C₀` semigroup. -/
theorem c0Semigroup_kernelSemigroup :
    R.isFellerKernelSemigroup_kernelSemigroup.c0Semigroup =
      R.toContractiveResolvent.generatedSemigroup :=
  PositiveC0SemigroupFeller.c0Semigroup_kernelSemigroup
    R.toContractiveResolvent.generatedSemigroup R.isPositive_generatedSemigroup

end Kernel

end PositiveC0ContractiveResolvent

end MarkovProcess
