/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
import MarkovProcess.Lifetime.Shift
import Mathlib.Probability.Process.Stopping

/-!
# Canonical filtration of lifetime paths

The raw canonical filtration is generated by the cemetery-valued coordinates up to each time.
The lifetime is a stopping time because death by time `t` is exactly the event that the time-`t`
coordinate is the cemetery state.
-/

open MeasureTheory
open scoped ENNReal

namespace MarkovProcess.LifetimePath

variable {alpha : Type*} [TopologicalSpace alpha] [MeasurableSpace alpha]

omit [MeasurableSpace alpha] in
/-- A coordinate is the cemetery state exactly at and after the lifetime. -/
theorem coordinate_eq_delta_iff (omega : LifetimePath alpha) (t : NNReal) :
    coordinate t omega = Cemetery.delta ↔ omega.lifetime ≤ (t : ENNReal) := by
  constructor
  · intro hcoordinate
    by_contra hlifetime
    exact coordinate_ne_delta_of_lt omega t (lt_of_not_ge hlifetime) hcoordinate
  · exact coordinate_of_le omega t

/-- The raw canonical filtration generated by lifetime-path coordinates up to time `t`. -/
def canonicalFiltration :
    Filtration NNReal (instMeasurableSpace (α := alpha)) where
  seq t := ⨆ s : Set.Iic t,
    MeasurableSpace.comap (coordinate (α := alpha) s) inferInstance
  mono' t u htu := by
    refine iSup_le fun s ↦ ?_
    exact le_iSup_of_le (⟨s.1, s.2.trans htu⟩ : Set.Iic u) le_rfl
  le' t := iSup_le fun s ↦ (measurable_coordinate s).comap_le

/-- The time-`t` coordinate is measurable for the canonical filtration at time `t`. -/
theorem measurable_coordinate_canonicalFiltration (t : NNReal) :
    Measurable[canonicalFiltration (alpha := alpha) t]
      (coordinate (α := alpha) t) := by
  apply Measurable.of_comap_le
  exact le_iSup_of_le (⟨t, Set.mem_Iic.mpr le_rfl⟩ : Set.Iic t) le_rfl

/-- Shifting by `S` sends events observable by shifted time `t` to events observable by original
time `S + t`. -/
theorem measurable_shift_canonicalFiltration (S t : NNReal) :
    Measurable[canonicalFiltration (alpha := alpha) (S + t),
      canonicalFiltration (alpha := alpha) t]
      (shift S : LifetimePath alpha → LifetimePath alpha) := by
  apply Measurable.of_comap_le
  rw [canonicalFiltration, MeasurableSpace.comap_iSup]
  rw [iSup_le_iff]
  intro u
  rw [MeasurableSpace.comap_comp]
  have hfun : coordinate (α := alpha) u ∘ shift S = coordinate (S + u) := by
    funext omega
    exact coordinate_shift S u omega
  rw [hfun]
  exact le_iSup_of_le
    (⟨S + u, by simpa only [add_comm] using add_le_add_left u.property S⟩ :
      Set.Iic (S + t)) le_rfl

/-- The lifetime is a stopping time for the raw canonical filtration. -/
theorem isStoppingTime_lifetime :
    IsStoppingTime (canonicalFiltration (alpha := alpha))
      (lifetime : LifetimePath alpha → ENNReal) := by
  intro t
  have hdelta : MeasurableSet ({Cemetery.delta} : Set (Cemetery alpha)) := by
    simpa only [Set.range_unique] using
      (measurableSet_range_inr :
        MeasurableSet (Set.range (Sum.inr : Unit → alpha ⊕ Unit)))
  have hevent : {omega : LifetimePath alpha | omega.lifetime ≤ (t : ENNReal)} =
      coordinate (α := alpha) t ⁻¹' {Cemetery.delta} := by
    ext omega
    simpa only [Set.mem_setOf_eq, Set.mem_preimage, Set.mem_singleton_iff] using
      (coordinate_eq_delta_iff omega t).symm
  convert (measurable_coordinate_canonicalFiltration t) hdelta using 1

end MarkovProcess.LifetimePath
