/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
import Mathlib.Topology.ContinuousMap.StoneWeierstrass
import Mathlib.Topology.ContinuousMap.CompactlySupported
import Mathlib.Topology.Separation.CompletelyRegular
import Mathlib.Topology.UrysohnsLemma

/-!
# Stone--Weierstrass on products

This file packages the subalgebra of real continuous functions on a finite product generated by
one-coordinate functions.  It proves that this subalgebra separates points, and hence is uniformly
dense when the factor is compact.

Membership in `PiContinuousMap.coordinateSubalgebra` expresses precisely that a
function is obtained from one-coordinate functions using finitely many constants, sums, and
products.  Thus the approximation theorem is a reusable bundled form of finite-product test
function density.

The coordinate pullback of a function in `C₀(α, ℝ)` need not itself vanish at infinity on the
whole product.  Accordingly, `coordinateC0Subalgebra` is a subalgebra of continuous maps; the
`C₀` designation records its one-coordinate generators, not its ambient carrier.
-/

open Topology
open scoped ZeroAtInfty

namespace MarkovProcess.PiContinuousMap

variable {I α : Type*} [TopologicalSpace α]

/-- Pull a continuous function on one factor back along a coordinate projection. -/
def coordinate (i : I) (f : C(α, ℝ)) : C(I → α, ℝ) :=
  f.comp ⟨fun x ↦ x i, continuous_apply i⟩

@[simp]
theorem coordinate_apply (i : I) (f : C(α, ℝ)) (x : I → α) :
    coordinate i f x = f (x i) :=
  rfl

/-- The algebra generated by pullbacks of continuous functions from individual factors. -/
def coordinateSubalgebra : Subalgebra ℝ C(I → α, ℝ) :=
  Algebra.adjoin ℝ {g | ∃ (i : I) (f : C(α, ℝ)), g = coordinate i f}

theorem coordinate_mem_coordinateSubalgebra (i : I) (f : C(α, ℝ)) :
    coordinate i f ∈ coordinateSubalgebra (I := I) (α := α) :=
  Algebra.subset_adjoin ⟨i, f, rfl⟩

/-- The algebra generated by coordinate pullbacks of functions vanishing at infinity. -/
def coordinateC0Subalgebra : Subalgebra ℝ C(I → α, ℝ) :=
  Algebra.adjoin ℝ
    {g | ∃ (i : I) (f : C₀(α, ℝ)), g = coordinate i (f : C(α, ℝ))}

theorem coordinate_c0_mem_coordinateC0Subalgebra (i : I) (f : C₀(α, ℝ)) :
    coordinate i (f : C(α, ℝ)) ∈ coordinateC0Subalgebra (I := I) (α := α) :=
  Algebra.subset_adjoin ⟨i, f, rfl⟩

/-- If continuous real functions separate points of the factor, the algebra generated by
one-coordinate functions separates points of every product. -/
theorem coordinateSubalgebra_separatesPoints [T35Space α] :
    (coordinateSubalgebra (I := I) (α := α)).SeparatesPoints := by
  intro x y hxy
  have hcoord : ∃ i : I, x i ≠ y i := by
    by_contra h
    apply hxy
    funext i
    exact not_ne_iff.mp (not_exists.mp h i)
  obtain ⟨i, hi⟩ := hcoord
  obtain ⟨f, hfcont, hfne⟩ := separatesPoints_continuous_of_t35Space hi
  let cf : C(α, ℝ) := ⟨f, hfcont⟩
  refine ⟨coordinate i cf, ?_, ?_⟩
  · exact ⟨coordinate i cf,
      ⟨coordinate_mem_coordinateSubalgebra (I := I) i cf, rfl⟩⟩
  · exact hfne

/-- On a locally compact regular factor, one-coordinate `C₀` functions already separate points
of every product. -/
theorem coordinateC0Subalgebra_separatesPoints
    [T3Space α] [LocallyCompactSpace α] :
    (coordinateC0Subalgebra (I := I) (α := α)).SeparatesPoints := by
  intro x y hxy
  have hcoord : ∃ i : I, x i ≠ y i := by
    by_contra h
    apply hxy
    funext i
    exact not_ne_iff.mp (not_exists.mp h i)
  obtain ⟨i, hi⟩ := hcoord
  obtain ⟨f, hfone, hfzero, hfcompact, -⟩ :=
    exists_continuous_one_zero_of_isCompact (isCompact_singleton : IsCompact ({x i} : Set α))
      (isClosed_singleton : IsClosed ({y i} : Set α)) (Set.disjoint_singleton.mpr hi)
  let f0 : C₀(α, ℝ) :=
    ⟨f, HasCompactSupport.is_zero_at_infty hfcompact⟩
  refine ⟨coordinate i (f0 : C(α, ℝ)), ?_, ?_⟩
  · exact ⟨coordinate i (f0 : C(α, ℝ)),
      ⟨coordinate_c0_mem_coordinateC0Subalgebra (I := I) i f0, rfl⟩⟩
  · change f (x i) ≠ f (y i)
    rw [hfone (Set.mem_singleton _),
      hfzero (Set.mem_singleton _)]
    exact one_ne_zero

/-- On every compact subset of a product, restrictions of globally continuous functions can be
approximated uniformly by algebraic combinations of one-coordinate `C₀` functions. -/
theorem exists_coordinateC0Subalgebra_near_on_isCompact
    [T3Space α] [LocallyCompactSpace α]
    (f : C(I → α, ℝ)) {K : Set (I → α)} (hK : IsCompact K)
    {epsilon : ℝ} (hepsilon : 0 < epsilon) :
    ∃ g ∈ coordinateC0Subalgebra (I := I) (α := α),
      ∀ x ∈ K, ‖g x - f x‖ < epsilon :=
  ContinuousMap.exists_mem_subalgebra_near_continuous_of_isCompact_of_separatesPoints
    coordinateC0Subalgebra_separatesPoints f hK hepsilon

/-- Finite algebraic combinations of one-coordinate continuous functions are uniformly dense in
the continuous real functions on a compact finite product. -/
theorem coordinateSubalgebra_topologicalClosure_eq_top
    [Fintype I] [T35Space α] [CompactSpace α] :
    (coordinateSubalgebra (I := I) (α := α)).topologicalClosure = ⊤ :=
  ContinuousMap.subalgebra_topologicalClosure_eq_top_of_separatesPoints _
    coordinateSubalgebra_separatesPoints

/-- Epsilon form of finite-product test-function density. -/
theorem exists_coordinateSubalgebra_near
    [Fintype I] [T35Space α] [CompactSpace α]
    (f : C(I → α, ℝ)) {epsilon : ℝ} (hepsilon : 0 < epsilon) :
    ∃ g : coordinateSubalgebra (I := I) (α := α),
      ‖(g : C(I → α, ℝ)) - f‖ < epsilon :=
  ContinuousMap.exists_mem_subalgebra_near_continuousMap_of_separatesPoints _
    coordinateSubalgebra_separatesPoints f epsilon hepsilon

end MarkovProcess.PiContinuousMap
