/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
import MarkovProcess.Path.ExitTimeShift

/-!
# Killing a continuous path at the exit time of a set

A continuous path `omega` and a set `U` determine a path with a lifetime: keep the path as long
as it stays in `U`, and send it to the cemetery from the exit time `ContinuousPath.exitTime U`
onwards.  This file defines that operation,

  `ContinuousPath.killAtExit U omega : LifetimePath U`,

whose lifetime is the exit time and whose live path is the original path read in the carrier `U`.

The main facts are the two coordinate formulas `coordinate_killAtExit_of_lt` and
`coordinate_killAtExit_of_le`, the shift identity `coordinate_killAtExit_shift` (before the exit
time, the coordinates of the killed shifted path are the later coordinates of the killed path),
and, for an open set `U`, the measurability `measurable_killAtExit` of the killing map for the
lifetime-path measurable structure generated by the lifetime and the coordinates.

This file constructs no probability law.
-/

open MeasureTheory
open scoped ENNReal NNReal

namespace MarkovProcess

section SubtypeImage

variable {alpha : Type*} (U : Set alpha)

/-- A point of `U` lies in the image of a set of the carrier `U` exactly when the corresponding
element of the carrier lies in that set. -/
theorem mem_image_val_iff {C : Set U} {y : alpha} (hy : y ∈ U) :
    y ∈ Subtype.val '' C ↔ (⟨y, hy⟩ : U) ∈ C := by
  rw [Subtype.coe_image, Set.mem_setOf_eq]
  exact ⟨fun h ↦ h.choose_spec, fun h ↦ ⟨hy, h⟩⟩

end SubtypeImage

namespace ContinuousPath

noncomputable section

variable {alpha : Type*} [PseudoMetricSpace alpha]

/-- The continuous path `omega` killed when it leaves `U`: the lifetime path whose lifetime is the
exit time of `U` and whose live path is `omega`, read as a path in the carrier `U`. -/
def killAtExit (U : Set alpha) (omega : ContinuousPath alpha) : LifetimePath U where
  lifetime := exitTime U omega
  livePath := fun t ↦ ⟨omega (t : NNReal), mem_of_lt_exitTime U omega (t : NNReal) t.property⟩
  continuous_livePath := by
    apply Continuous.subtype_mk
    exact omega.continuous.comp continuous_subtype_val

@[simp]
theorem lifetime_killAtExit (U : Set alpha) (omega : ContinuousPath alpha) :
    (killAtExit U omega).lifetime = exitTime U omega :=
  rfl

/-- Strictly before the exit time, the killed path is alive at the position of the original
path. -/
theorem coordinate_killAtExit_of_lt (U : Set alpha) (omega : ContinuousPath alpha) (t : NNReal)
    (ht : (t : ℝ≥0∞) < exitTime U omega) :
    LifetimePath.coordinate t (killAtExit U omega) =
      Cemetery.alive ⟨omega t, mem_of_lt_exitTime U omega t ht⟩ :=
  LifetimePath.coordinate_of_lt (killAtExit U omega) t ht

/-- From the exit time onwards, the killed path sits at the cemetery. -/
theorem coordinate_killAtExit_of_le (U : Set alpha) (omega : ContinuousPath alpha) (t : NNReal)
    (ht : exitTime U omega ≤ (t : ℝ≥0∞)) :
    LifetimePath.coordinate t (killAtExit U omega) = Cemetery.delta :=
  LifetimePath.coordinate_of_le (killAtExit U omega) t ht

/-- Once the path has left `U` by time `t`, every later coordinate of the killed path is the
cemetery state. -/
theorem coordinate_killAtExit_of_exitTime_le (U : Set alpha) (omega : ContinuousPath alpha)
    {t s : NNReal} (ht : exitTime U omega ≤ (t : ℝ≥0∞)) (hts : t ≤ s) :
    LifetimePath.coordinate s (killAtExit U omega) = Cemetery.delta :=
  coordinate_killAtExit_of_le U omega s (ht.trans (ENNReal.coe_le_coe.mpr hts))

/-- The coordinates of the killed path, in closed form. -/
theorem coordinate_killAtExit (U : Set alpha) (omega : ContinuousPath alpha) (t : NNReal) :
    LifetimePath.coordinate t (killAtExit U omega) =
      if ht : (t : ℝ≥0∞) < exitTime U omega then
        Cemetery.alive ⟨omega t, mem_of_lt_exitTime U omega t ht⟩
      else Cemetery.delta := by
  by_cases ht : (t : ℝ≥0∞) < exitTime U omega
  · rw [dif_pos ht, coordinate_killAtExit_of_lt U omega t ht]
  · rw [dif_neg ht, coordinate_killAtExit_of_le U omega t (not_lt.mp ht)]

/-- **Shift identity for the killed path.**  Strictly before the exit time of `U`, killing the
path shifted by `t` and reading it at time `s` is the same as killing the path and reading it at
time `t + s`. -/
theorem coordinate_killAtExit_shift (U : Set alpha) (omega : ContinuousPath alpha) (t s : NNReal)
    (ht : (t : ℝ≥0∞) < exitTime U omega) :
    LifetimePath.coordinate s (killAtExit U (shift t omega)) =
      LifetimePath.coordinate (t + s) (killAtExit U omega) := by
  by_cases hs : (s : ℝ≥0∞) < exitTime U (shift t omega)
  · have hts : ((t + s : NNReal) : ℝ≥0∞) < exitTime U omega :=
      (coe_add_lt_exitTime_iff U omega t s).mpr ⟨ht, hs⟩
    rw [coordinate_killAtExit_of_lt U (shift t omega) s hs,
      coordinate_killAtExit_of_lt U omega (t + s) hts]
    exact congrArg Cemetery.alive (Subtype.ext (shift_apply t s omega))
  · have hts : ¬ ((t + s : NNReal) : ℝ≥0∞) < exitTime U omega := fun h ↦
      hs ((coe_add_lt_exitTime_iff U omega t s).mp h).2
    rw [coordinate_killAtExit_of_le U (shift t omega) s (not_lt.mp hs),
      coordinate_killAtExit_of_le U omega (t + s) (not_lt.mp hts)]

section Preimage

variable (U : Set alpha) (t : NNReal)

/-- The event that the killed path is alive at time `t` and its live coordinate lies in `S`. -/
theorem preimage_coordinate_killAtExit_of_notMem {S : Set (Cemetery U)}
    (hS : (Cemetery.delta : Cemetery U) ∉ S) :
    (fun omega ↦ LifetimePath.coordinate t (killAtExit U omega)) ⁻¹' S =
      {omega : ContinuousPath alpha | (t : ℝ≥0∞) < exitTime U omega ∧
        omega t ∈ Subtype.val '' (Cemetery.alive ⁻¹' S)} := by
  ext omega
  rw [Set.mem_preimage, coordinate_killAtExit, Set.mem_setOf_eq]
  by_cases ht : (t : ℝ≥0∞) < exitTime U omega
  · rw [dif_pos ht]
    have hmem := mem_image_val_iff U (C := Cemetery.alive ⁻¹' S)
      (mem_of_lt_exitTime U omega t ht)
    rw [hmem]
    exact ⟨fun h ↦ ⟨ht, h⟩, fun h ↦ h.2⟩
  · rw [dif_neg ht]
    exact ⟨fun h ↦ absurd h hS, fun h ↦ absurd h.1 ht⟩

/-- The event that the killed path is at the cemetery at time `t`, or is alive with live
coordinate in `S`. -/
theorem preimage_coordinate_killAtExit_of_mem {S : Set (Cemetery U)}
    (hS : (Cemetery.delta : Cemetery U) ∈ S) :
    (fun omega ↦ LifetimePath.coordinate t (killAtExit U omega)) ⁻¹' S =
      {omega : ContinuousPath alpha | (t : ℝ≥0∞) < exitTime U omega ∧
          omega t ∈ Subtype.val '' (Cemetery.alive ⁻¹' S)} ∪
        {omega : ContinuousPath alpha | ¬ (t : ℝ≥0∞) < exitTime U omega} := by
  ext omega
  rw [Set.mem_preimage, coordinate_killAtExit, Set.mem_union, Set.mem_setOf_eq, Set.mem_setOf_eq]
  by_cases ht : (t : ℝ≥0∞) < exitTime U omega
  · rw [dif_pos ht]
    have hmem := mem_image_val_iff U (C := Cemetery.alive ⁻¹' S)
      (mem_of_lt_exitTime U omega t ht)
    rw [hmem]
    constructor
    · exact fun h ↦ Or.inl ⟨ht, h⟩
    · rintro (h | h)
      · exact h.2
      · exact absurd ht h
  · rw [dif_neg ht]
    exact ⟨fun _ ↦ Or.inr ht, fun _ ↦ hS⟩

end Preimage

section Measurable

variable [MeasurableSpace alpha] [BorelSpace alpha]

/-- Every fixed-time coordinate of the path killed at the exit of an open set is measurable. -/
theorem measurable_coordinate_killAtExit (U : Set alpha) (hU : IsOpen U) (t : NNReal) :
    Measurable fun omega : ContinuousPath alpha ↦
      LifetimePath.coordinate t (killAtExit U omega) := by
  intro S hS
  have hC : MeasurableSet (Subtype.val '' (Cemetery.alive ⁻¹' S)) :=
    (MeasurableEmbedding.subtype_coe hU.measurableSet).measurableSet_image.mpr
      (measurable_inl hS)
  have hlive : MeasurableSet {omega : ContinuousPath alpha |
      (t : ℝ≥0∞) < exitTime U omega ∧ omega t ∈ Subtype.val '' (Cemetery.alive ⁻¹' S)} :=
    (measurableSet_lt_exitTime U hU t).inter
      ((measurable_coordinateProcess (alpha := alpha) t) hC)
  by_cases hdelta : (Cemetery.delta : Cemetery U) ∈ S
  · rw [preimage_coordinate_killAtExit_of_mem U t hdelta]
    refine hlive.union ?_
    have hcompl : {omega : ContinuousPath alpha | ¬ (t : ℝ≥0∞) < exitTime U omega} =
        {omega : ContinuousPath alpha | (t : ℝ≥0∞) < exitTime U omega}ᶜ := rfl
    rw [hcompl]
    exact (measurableSet_lt_exitTime U hU t).compl
  · rw [preimage_coordinate_killAtExit_of_notMem U t hdelta]
    exact hlive

/-- **Killing at the exit time of an open set is measurable** for the measurable structure on
lifetime paths generated by the lifetime and the fixed-time coordinates. -/
theorem measurable_killAtExit (U : Set alpha) (hU : IsOpen U) :
    Measurable (killAtExit U : ContinuousPath alpha → LifetimePath U) := by
  apply Measurable.of_comap_le
  rw [LifetimePath.instMeasurableSpace, MeasurableSpace.comap_sup, MeasurableSpace.comap_iSup]
  apply sup_le
  · rw [MeasurableSpace.comap_comp]
    have hfun : LifetimePath.lifetime ∘ (killAtExit U : ContinuousPath alpha → LifetimePath U) =
        exitTime U := rfl
    rw [hfun]
    exact (measurable_exitTime U hU).comap_le
  · rw [iSup_le_iff]
    intro t
    rw [MeasurableSpace.comap_comp]
    exact (measurable_coordinate_killAtExit U hU t).comap_le

end Measurable

end

end ContinuousPath

end MarkovProcess
