/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
import Mathlib.Probability.Process.Filtration
import Mathlib.Topology.CompactOpen

/-!
# Canonical continuous-path space

This file provides the compact-open space of continuous paths on nonnegative real time, its
coordinate process, and the filtration generated by coordinates up to each time. It constructs
no probability law and makes no stochastic-process association or path-regularity claim.
-/

open MeasureTheory

namespace MarkovProcess

/-- Continuous paths on nonnegative real time, with the compact-open topology. -/
abbrev ContinuousPath (alpha : Type*) [TopologicalSpace alpha] := C(NNReal, alpha)

namespace ContinuousPath

variable {alpha : Type*} [TopologicalSpace alpha]

/-- The Borel sigma-algebra of the compact-open topology on continuous paths. -/
instance instMeasurableSpace : MeasurableSpace (ContinuousPath alpha) := borel _

/-- Continuous-path space carries its Borel sigma-algebra. -/
instance instBorelSpace : BorelSpace (ContinuousPath alpha) := ⟨rfl⟩

/-- Evaluation of a continuous path at a fixed nonnegative time. -/
def eval (t : NNReal) : ContinuousPath alpha → alpha := fun omega => omega t

@[simp]
theorem eval_apply (t : NNReal) (omega : ContinuousPath alpha) : eval t omega = omega t := rfl

/-- Fixed-time evaluation is continuous for the compact-open topology. -/
theorem continuous_eval (t : NNReal) : Continuous (eval (alpha := alpha) t) :=
  continuous_eval_const t

/-- The coordinate process on canonical continuous-path space. -/
def coordinateProcess (t : NNReal) (omega : ContinuousPath alpha) : alpha := omega t

@[simp]
theorem coordinateProcess_apply (t : NNReal) (omega : ContinuousPath alpha) :
    coordinateProcess t omega = omega t := rfl

/-- Every fixed-time coordinate of the canonical process is continuous. -/
theorem continuous_coordinateProcess (t : NNReal) :
    Continuous (coordinateProcess (alpha := alpha) t) :=
  continuous_eval_const t

/-- Every fixed-time coordinate is Borel measurable. -/
theorem measurable_coordinateProcess [MeasurableSpace alpha] [BorelSpace alpha] (t : NNReal) :
    Measurable[borel (ContinuousPath alpha)] (coordinateProcess (alpha := alpha) t) :=
  (continuous_coordinateProcess t).borel_measurable.mono le_rfl
    (le_of_eq BorelSpace.measurable_eq)

/-- Two continuous paths are equal when all of their time coordinates agree. -/
@[ext]
theorem ext {omega eta : ContinuousPath alpha} (h : ∀ t, omega t = eta t) : omega = eta :=
  ContinuousMap.ext h

/-- The canonical filtration generated by coordinates at times `s ≤ t`. -/
def canonicalFiltration [MeasurableSpace alpha] [BorelSpace alpha] :
    Filtration NNReal (borel (ContinuousPath alpha)) where
  seq t := ⨆ s : Set.Iic t,
    MeasurableSpace.comap (coordinateProcess (alpha := alpha) s) ‹MeasurableSpace alpha›
  mono' t u htu := by
    refine iSup_le fun s => ?_
    exact le_iSup_of_le (⟨s.1, s.2.trans htu⟩ : Set.Iic u) le_rfl
  le' t := iSup_le fun s => (measurable_coordinateProcess s).comap_le

/-- The time-`t` coordinate is measurable for the canonical filtration at time `t`. -/
theorem measurable_coordinateProcess_canonicalFiltration
    [MeasurableSpace alpha] [BorelSpace alpha] (t : NNReal) :
    Measurable[canonicalFiltration (alpha := alpha) t]
      (coordinateProcess (alpha := alpha) t) := by
  apply Measurable.of_comap_le
  exact le_iSup_of_le (⟨t, Set.mem_Iic.mpr le_rfl⟩ : Set.Iic t) le_rfl

end ContinuousPath

end MarkovProcess
