/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
import MarkovProcess.Semigroup.Generation
import MarkovProcess.Semigroup.GeneratorInjectivity

/-!
# The generator of the semigroup generated by a contractive resolvent

Let `R` be a contractive resolvent on a Banach space, `S = R.generatedSemigroup` the strongly
continuous contraction semigroup obtained from its Yosida approximations, and `L = S.generator`.
This file identifies `L` as the operator whose resolvent is `R`, which is the identification half
of the Hille--Yosida theorem:

* `operator_mem_generatorDomain` and `generator_operator_apply`: the range of every `R_μ` lies in
  the generator domain, with `L (R_μ y) = μ R_μ y - y`;
* `generatorDomain_eq_range`: the generator domain is exactly the range of `R_μ`, for every
  positive shift `μ`;
* `operator_smul_sub_generator`: `R_μ (μ f - L f) = f` for every `f` of the domain, and
  `generator_apply_of_operator_eq`: `L (R_μ g) = μ R_μ g - g` read from the other side.

Thus `R_μ = (μ - L)⁻¹` with domain `range R_μ`: this is the `(μ + A)⁻¹` convention of
`ContractiveResolvent` with `A = -L`.

The route to the first item is the fundamental identity `S_n t x - x = ∫₀ᵗ S_n s (A_n x) ds` for
the bounded Yosida approximations `S_n = exp (t A_n)`, which is elementary calculus for a Banach
algebra exponential (`yosidaOperator_apply_sub_eq_integral`); passing to the limit along the
canonical shifts by dominated convergence gives `S t x - x = ∫₀ᵗ S s (μ x - y) ds` on the range of
`R_μ`, and time averages of the orbit then produce the difference quotient at `t = 0`.
-/

open Filter MeasureTheory NormedSpace Set Topology
open scoped NNReal

noncomputable section

namespace MarkovProcess.Semigroup

namespace ContractiveResolvent

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]

/-- **The fundamental identity for a bounded Yosida approximation.**  The exponential semigroup
of the bounded generator `A_α` satisfies `exp (t A_α) x - x = ∫₀ᵗ exp (s A_α) (A_α x) ds` for
every vector `x`, by the fundamental theorem of calculus for the Banach-algebra exponential. -/
theorem yosidaOperator_apply_sub_eq_integral (R : ContractiveResolvent E)
    (α : PositiveShift) (t : NNReal) (x : E) :
    R.yosidaOperator α t x - x =
      ∫ s in (0 : ℝ)..(t : ℝ), R.yosidaOperator α (Real.toNNReal s) (R.yosidaGenerator α x) := by
  have hderiv : ∀ s : ℝ, HasDerivAt (fun u : ℝ ↦ exp ℝ (u • R.yosidaGenerator α) x)
      (exp ℝ (s • R.yosidaGenerator α) (R.yosidaGenerator α x)) s := by
    intro s
    have h := (hasDerivAt_exp_smul_const (𝕂 := ℝ) (R.yosidaGenerator α) s).clm_apply
      (hasDerivAt_const s x)
    simpa only [ContinuousLinearMap.mul_apply, map_zero, add_zero] using h
  have hcont : Continuous fun s : ℝ ↦
      exp ℝ (s • R.yosidaGenerator α) (R.yosidaGenerator α x) := by fun_prop
  have hFTC := intervalIntegral.integral_eq_sub_of_hasDerivAt (fun s _ ↦ hderiv s)
    (hcont.intervalIntegrable 0 (t : ℝ))
  have hcongr :
      (∫ s in (0 : ℝ)..(t : ℝ), R.yosidaOperator α (Real.toNNReal s) (R.yosidaGenerator α x)) =
        ∫ s in (0 : ℝ)..(t : ℝ), exp ℝ (s • R.yosidaGenerator α) (R.yosidaGenerator α x) := by
    refine intervalIntegral.integral_congr fun s hs ↦ ?_
    rw [Set.uIcc_of_le t.coe_nonneg] at hs
    unfold yosidaOperator
    rw [Real.coe_toNNReal s hs.1]
  rw [hcongr, hFTC]
  unfold yosidaOperator
  rw [zero_smul, exp_zero]
  rfl

/-- **The fundamental identity on the range of a resolvent.**  For the generated semigroup `S`,
`S t (R_μ y) - R_μ y = ∫₀ᵗ S s (μ R_μ y - y) ds`.  Both sides are limits along the canonical
shifts of the corresponding Yosida quantities, the integrals converging by dominated
convergence: the integrands are contractions applied to the convergent sequence
`A_n (R_μ y) → μ R_μ y - y`. -/
theorem generatedSemigroup_apply_sub_eq_orbitIntegral (R : ContractiveResolvent E)
    (μ : PositiveShift) (y : E) (t : NNReal) :
    R.generatedSemigroup t (R.operator μ y) - R.operator μ y =
      R.generatedSemigroup.orbitIntegral ((μ : ℝ) • R.operator μ y - y) t := by
  obtain ⟨C, hC⟩ :=
    (R.cauchySeq_yosidaGenerator_naturalShift_apply_operator μ y).isBounded_range.exists_norm_le
  have hnorm : ∀ (n : ℕ) (s : ℝ), ‖R.yosidaOperator (naturalShift n) (Real.toNNReal s)
      (R.yosidaGenerator (naturalShift n) (R.operator μ y))‖ ≤ C := by
    intro n s
    refine le_trans ?_ (hC _ ⟨n, rfl⟩)
    simpa only [yosidaSemigroup_apply] using
      (R.yosidaSemigroup (naturalShift n)).norm_apply_le (Real.toNNReal s)
        (R.yosidaGenerator (naturalShift n) (R.operator μ y))
  have hmeas : ∀ n : ℕ, AEStronglyMeasurable
      (fun s : ℝ ↦ R.yosidaOperator (naturalShift n) (Real.toNNReal s)
        (R.yosidaGenerator (naturalShift n) (R.operator μ y)))
      (volume.restrict (Set.uIoc (0 : ℝ) (t : ℝ))) := by
    intro n
    exact ((R.continuous_yosidaOperator_apply (naturalShift n) _).comp
      continuous_real_toNNReal).aestronglyMeasurable
  have hpointwise : ∀ s : ℝ, Tendsto (fun n ↦ R.yosidaOperator (naturalShift n) (Real.toNNReal s)
      (R.yosidaGenerator (naturalShift n) (R.operator μ y))) atTop
      (nhds (R.generatedSemigroup (Real.toNNReal s) ((μ : ℝ) • R.operator μ y - y))) := by
    intro s
    exact tendsto_apply_of_opNorm_le_one
      (fun n ↦ R.yosidaOperator (naturalShift n) (Real.toNNReal s))
      (R.generatedSemigroup (Real.toNNReal s))
      (fun n ↦ R.yosidaGenerator (naturalShift n) (R.operator μ y))
      ((μ : ℝ) • R.operator μ y - y)
      (fun n ↦ R.norm_yosidaOperator_le_one (naturalShift n) (Real.toNNReal s))
      (R.tendsto_yosidaOperator_naturalShift_apply (Real.toNNReal s) _)
      (R.tendsto_yosidaGenerator_naturalShift_apply_operator μ y)
  have hlimR : Tendsto (fun n ↦ ∫ s in (0 : ℝ)..(t : ℝ),
      R.yosidaOperator (naturalShift n) (Real.toNNReal s)
        (R.yosidaGenerator (naturalShift n) (R.operator μ y))) atTop
      (nhds (R.generatedSemigroup.orbitIntegral ((μ : ℝ) • R.operator μ y - y) t)) := by
    rw [StronglyContinuousContractionSemigroup.orbitIntegral_apply]
    exact intervalIntegral.tendsto_integral_filter_of_dominated_convergence (fun _ ↦ C)
      (Eventually.of_forall hmeas)
      (Eventually.of_forall fun n ↦ Eventually.of_forall fun s _ ↦ hnorm n s)
      intervalIntegrable_const
      (Eventually.of_forall fun s _ ↦ hpointwise s)
  refine tendsto_nhds_unique
    ((R.tendsto_yosidaOperator_naturalShift_apply t (R.operator μ y)).sub tendsto_const_nhds)
    (hlimR.congr fun n ↦ ?_)
  exact (R.yosidaOperator_apply_sub_eq_integral (naturalShift n) t (R.operator μ y)).symm

/-- The range of every resolvent lies in the generator domain of the generated semigroup. -/
theorem operator_mem_generatorDomain (R : ContractiveResolvent E) (μ : PositiveShift) (y : E) :
    R.operator μ y ∈ R.generatedSemigroup.generatorDomain := by
  refine R.generatedSemigroup.mem_generatorDomain_of_tendsto
    (g := (μ : ℝ) • R.operator μ y - y) ?_
  refine (R.generatedSemigroup.tendsto_inv_smul_orbitIntegral
    ((μ : ℝ) • R.operator μ y - y)).congr fun t ↦ ?_
  rw [R.generatedSemigroup_apply_sub_eq_orbitIntegral μ y t]

/-- **The generator inverts the resolvent.**  On the range of `R_μ`, the generator of the
generated semigroup is `L (R_μ y) = μ R_μ y - y`. -/
theorem generator_operator_apply (R : ContractiveResolvent E) (μ : PositiveShift) (y : E) :
    R.generatedSemigroup.generator ⟨R.operator μ y, R.operator_mem_generatorDomain μ y⟩ =
      (μ : ℝ) • R.operator μ y - y := by
  refine R.generatedSemigroup.generator_eq_of_tendsto _ ?_
  refine (R.generatedSemigroup.tendsto_inv_smul_orbitIntegral
    ((μ : ℝ) • R.operator μ y - y)).congr fun t ↦ ?_
  rw [R.generatedSemigroup_apply_sub_eq_orbitIntegral μ y t]

/-- The generator on a vector presented as a resolvent image: if `R_μ g = f`, then
`L f = μ f - g`. -/
theorem generator_apply_of_operator_eq (R : ContractiveResolvent E) (μ : PositiveShift) {f g : E}
    (hf : f ∈ R.generatedSemigroup.generatorDomain) (hfg : R.operator μ g = f) :
    R.generatedSemigroup.generator ⟨f, hf⟩ = (μ : ℝ) • f - g := by
  subst hfg
  exact R.generator_operator_apply μ g

/-- **The resolvent inverts `μ - L`.**  For every vector `f` of the generator domain of the
generated semigroup, `R_μ (μ f - L f) = f`. -/
theorem operator_smul_sub_generator (R : ContractiveResolvent E) (μ : PositiveShift)
    (f : R.generatedSemigroup.generatorDomain) :
    R.operator μ ((μ : ℝ) • (f : E) - R.generatedSemigroup.generator f) = (f : E) := by
  refine R.generatedSemigroup.eq_of_smul_sub_generator_eq μ.property
    ⟨R.operator μ ((μ : ℝ) • (f : E) - R.generatedSemigroup.generator f),
      R.operator_mem_generatorDomain μ _⟩ f ?_
  rw [R.generator_operator_apply μ ((μ : ℝ) • (f : E) - R.generatedSemigroup.generator f)]
  abel

/-- **The generator domain is the range of any resolvent.**  Together with
`operator_smul_sub_generator` this says that `R_μ` is a bijection from `E` onto the generator
domain, inverse to `μ - L`. -/
theorem generatorDomain_eq_range (R : ContractiveResolvent E) (μ : PositiveShift) :
    (R.generatedSemigroup.generatorDomain : Set E) = Set.range (R.operator μ) := by
  refine Set.Subset.antisymm (fun f hf ↦ ?_) ?_
  · exact ⟨(μ : ℝ) • f - R.generatedSemigroup.generator ⟨f, hf⟩,
      R.operator_smul_sub_generator μ ⟨f, hf⟩⟩
  · rintro _ ⟨y, rfl⟩
    exact R.operator_mem_generatorDomain μ y

end ContractiveResolvent

end MarkovProcess.Semigroup

end
