/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
import MarkovProcess.Semigroup.Resolvent
import MarkovProcess.Semigroup.GeneratorResolvent
import MarkovProcess.Semigroup.GeneratorUniqueness

/-!
# The semigroup generated by the resolvent of a semigroup

The two halves of the Hille–Yosida correspondence close up: the contractive resolvent of a
strongly continuous contraction semigroup `S` (`Semigroup/Resolvent.lean`) generates, through
`Semigroup/Generation.lean`, a semigroup whose generator is the generator of `S`
(`Semigroup/GeneratorResolvent.lean`, `generatorDomain_eq_range_resolvent`), and a strongly
continuous contraction semigroup is determined by its generator
(`Semigroup/GeneratorUniqueness.lean`).  Hence the generated semigroup is `S` itself
(`generatedSemigroup_toContractiveResolvent`).

Conversely the resolvent of the semigroup generated by a contractive resolvent `R` is `R`
(`ContractiveResolvent.resolvent_generatedSemigroup`), because both invert `μ − L` and `μ − L` is
injective.

Main results: `generatorDomain_generatedSemigroup_toContractiveResolvent`,
`generatedSemigroup_toContractiveResolvent`, `ContractiveResolvent.resolvent_generatedSemigroup`,
`ContractiveResolvent.toContractiveResolvent_generatedSemigroup`.

Nothing is asserted about resolvents that do not come from a semigroup; for those, the
generation theorem of `Semigroup/Generation.lean` is the statement.
-/

open scoped NNReal

namespace MarkovProcess.Semigroup.StronglyContinuousContractionSemigroup

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
variable (S : StronglyContinuousContractionSemigroup E)

/-- The semigroup generated by the resolvent of `S` has the generator domain of `S`. -/
theorem generatorDomain_generatedSemigroup_toContractiveResolvent :
    S.toContractiveResolvent.generatedSemigroup.generatorDomain = S.generatorDomain := by
  have μ₁ : PositiveShift := ⟨1, Set.mem_Ioi.mpr one_pos⟩
  apply SetLike.coe_injective
  exact (S.toContractiveResolvent.generatorDomain_eq_range μ₁).trans
    (S.generatorDomain_eq_range_resolvent μ₁).symm

/-- **The semigroup generated by the resolvent of `S` is `S`.** -/
theorem generatedSemigroup_toContractiveResolvent :
    S.toContractiveResolvent.generatedSemigroup = S := by
  have μ₁ : PositiveShift := ⟨1, Set.mem_Ioi.mpr one_pos⟩
  refine S.toContractiveResolvent.generatedSemigroup.ext_of_generator S
    S.generatorDomain_generatedSemigroup_toContractiveResolvent ?_
  intro f hT hS
  obtain ⟨g, rfl⟩ : f ∈ Set.range (S.resolvent μ₁) := by
    rw [← S.generatorDomain_eq_range_resolvent μ₁]
    exact hS
  rw [S.toContractiveResolvent.generator_apply_of_operator_eq μ₁ (g := g) hT rfl,
    S.generator_eq_of_resolvent_eq μ₁ hS rfl]

end MarkovProcess.Semigroup.StronglyContinuousContractionSemigroup

namespace MarkovProcess.Semigroup.ContractiveResolvent

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]

/-- **The resolvent of the generated semigroup is the given resolvent.** -/
theorem resolvent_generatedSemigroup (R : ContractiveResolvent E) (μ : PositiveShift) :
    R.generatedSemigroup.resolvent μ = R.operator μ := by
  ext y
  apply R.generatedSemigroup.eq_of_smul_sub_generator_eq μ.2
    ⟨R.generatedSemigroup.resolvent μ y, R.generatedSemigroup.resolvent_mem_generatorDomain μ y⟩
    ⟨R.operator μ y, R.operator_mem_generatorDomain μ y⟩
  rw [R.generatedSemigroup.generator_resolvent μ y, R.generator_operator_apply μ y]
  simp only [sub_sub_cancel]

/-- The contractive resolvent of the generated semigroup is the given contractive resolvent. -/
theorem toContractiveResolvent_generatedSemigroup (R : ContractiveResolvent E) :
    R.generatedSemigroup.toContractiveResolvent = R := by
  cases R
  simp only [StronglyContinuousContractionSemigroup.toContractiveResolvent,
    ContractiveResolvent.mk.injEq]
  funext μ
  exact resolvent_generatedSemigroup _ μ

end MarkovProcess.Semigroup.ContractiveResolvent
