/-
Copyright (c) 2026 Scott Armstrong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong
-/
import MarkovProcess.Semigroup.GeneratorClosed
import MarkovProcess.Semigroup.GeneratorInjectivity
import MarkovProcess.Semigroup.ContractiveResolvent
import Mathlib.MeasureTheory.Integral.ExpDecay
import Mathlib.Analysis.SpecialFunctions.ImproperIntegrals

/-!
# The resolvent of a strongly continuous contraction semigroup

For a strongly continuous contraction semigroup `S` on a real Banach space and a positive shift
`μ`, the resolvent is the Laplace transform of the orbits,

  `S.resolvent μ x = ∫₀^∞ e^{-μ t} S t x dt`,

a bounded operator of norm at most `μ⁻¹` (`opNorm_resolvent_le`).  The resolvent inverts `μ − L`
on the generator domain, `R_μ (μ f − L f) = f` (`resolvent_smul_sub_generator`, by the product
rule and the fundamental theorem of calculus on `[0, ∞)`), and `μ − L` inverts it on the whole
space: `R_μ x` lies in the domain with `L (R_μ x) = μ R_μ x − x` (`resolvent_mem_generatorDomain`,
`generator_resolvent`).  The latter is proved first for `x` in the domain, where `R_μ` commutes
with the difference quotients, and extended to all `x` by density of the domain and closedness of
the generator (`Semigroup/GeneratorClosed.lean`).

Consequently the domain is the range of every resolvent (`generatorDomain_eq_range_resolvent`),
the resolvents satisfy the resolvent identity (`resolvent_sub_resolvent`) and have dense range
(`denseRange_resolvent`), so they form a contractive resolvent in the sense of
`Semigroup/ContractiveResolvent.lean` (`toContractiveResolvent`).  That the semigroup generated by
this contractive resolvent is `S` itself is proved in `Semigroup/ResolventGeneration.lean`.

Main results: `laplaceIntegrand` and its integrability, `resolvent`, `resolvent_apply`,
`opNorm_resolvent_le`, `operator_resolvent`, `resolvent_smul_sub_generator`,
`resolvent_mem_generatorDomain`, `generator_resolvent`, `generator_eq_of_resolvent_eq`,
`generatorDomain_eq_range_resolvent`, `resolvent_sub_resolvent`, `denseRange_resolvent`,
`toContractiveResolvent`.

The shift `μ` is a positive real; nothing is asserted for complex shifts or for the spectrum of the
generator beyond the half-line `(0, ∞)`.
-/

open MeasureTheory Filter Topology Set
open scoped NNReal

namespace MarkovProcess.Semigroup.StronglyContinuousContractionSemigroup

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
variable (S : StronglyContinuousContractionSemigroup E)

noncomputable section

section Integrand

/-- The integrand of the Laplace transform of the orbit of `x` at the shift `μ`, read in the real
time variable. -/
def laplaceIntegrand (μ : ℝ) (x : E) (t : ℝ) : E := Real.exp (-μ * t) • S (Real.toNNReal t) x

omit [CompleteSpace E] in
/-- The Laplace integrand, unfolded. -/
theorem laplaceIntegrand_apply (μ : ℝ) (x : E) (t : ℝ) :
    S.laplaceIntegrand μ x t = Real.exp (-μ * t) • S (Real.toNNReal t) x :=
  rfl

omit [CompleteSpace E] in
/-- The Laplace integrand is continuous in time. -/
theorem continuous_laplaceIntegrand (μ : ℝ) (x : E) : Continuous (S.laplaceIntegrand μ x) :=
  (Real.continuous_exp.comp (continuous_const.mul continuous_id)).smul
    (S.continuous_operator_toNNReal x)

omit [CompleteSpace E] in
/-- The Laplace integrand is dominated by the exponential weight. -/
theorem norm_laplaceIntegrand_le (μ : ℝ) (x : E) (t : ℝ) :
    ‖S.laplaceIntegrand μ x t‖ ≤ Real.exp (-μ * t) * ‖x‖ := by
  rw [laplaceIntegrand_apply, norm_smul, Real.norm_eq_abs, abs_of_pos (Real.exp_pos _)]
  exact mul_le_mul_of_nonneg_left (S.norm_apply_le _ x) (Real.exp_pos _).le

omit [CompleteSpace E] in
/-- The Laplace integrand is integrable on `(0, ∞)` for a positive shift. -/
theorem integrableOn_laplaceIntegrand {μ : ℝ} (hμ : 0 < μ) (x : E) :
    IntegrableOn (S.laplaceIntegrand μ x) (Ioi 0) :=
  Integrable.mono' ((exp_neg_integrableOn_Ioi 0 hμ).mul_const ‖x‖)
    (S.continuous_laplaceIntegrand μ x).aestronglyMeasurable.restrict
    (Eventually.of_forall fun t ↦ S.norm_laplaceIntegrand_le μ x t)

omit [CompleteSpace E] in
/-- The Laplace integrand is additive in the vector. -/
theorem laplaceIntegrand_add (μ : ℝ) (x y : E) :
    S.laplaceIntegrand μ (x + y) = S.laplaceIntegrand μ x + S.laplaceIntegrand μ y := by
  funext t
  simp only [laplaceIntegrand_apply, map_add, smul_add, Pi.add_apply]

omit [CompleteSpace E] in
/-- The Laplace integrand is homogeneous in the vector. -/
theorem laplaceIntegrand_smul (μ : ℝ) (c : ℝ) (x : E) :
    S.laplaceIntegrand μ (c • x) = c • S.laplaceIntegrand μ x := by
  funext t
  simp only [laplaceIntegrand_apply, map_smul, Pi.smul_apply]
  exact smul_comm _ _ _

omit [CompleteSpace E] in
/-- The semigroup commutes with the Laplace integrand. -/
theorem laplaceIntegrand_operator (μ : ℝ) (h : NNReal) (x : E) (t : ℝ) :
    S h (S.laplaceIntegrand μ x t) = S.laplaceIntegrand μ (S h x) t := by
  simp only [laplaceIntegrand_apply, map_smul, S.commute_apply]

omit [CompleteSpace E] in
/-- The Laplace integrand tends to zero at infinity for a positive shift. -/
theorem tendsto_laplaceIntegrand_atTop {μ : ℝ} (hμ : 0 < μ) (x : E) :
    Tendsto (S.laplaceIntegrand μ x) atTop (𝓝 0) := by
  have hexp : Tendsto (fun t : ℝ ↦ Real.exp (-μ * t)) atTop (𝓝 0) := by
    have := Real.tendsto_exp_atBot.comp
      (tendsto_neg_atTop_atBot.comp (tendsto_id.const_mul_atTop hμ))
    refine this.congr fun t ↦ ?_
    simp only [Function.comp, id, neg_mul]
  refine squeeze_zero_norm (fun t ↦ S.norm_laplaceIntegrand_le μ x t) ?_
  simpa using hexp.mul_const ‖x‖

/-- The Laplace transform of the exponential weight. -/
theorem integral_exp_neg_mul_Ioi_zero {μ : ℝ} (hμ : 0 < μ) :
    ∫ t in Ioi (0 : ℝ), Real.exp (-μ * t) = μ⁻¹ := by
  have h := integral_comp_mul_left_Ioi (fun t : ℝ ↦ Real.exp (-t)) 0 hμ
  simp only [mul_zero, integral_exp_neg_Ioi_zero, smul_eq_mul, mul_one] at h
  rw [← h]
  refine setIntegral_congr_fun measurableSet_Ioi fun t _ ↦ ?_
  rw [neg_mul]

omit [CompleteSpace E] in
/-- The Laplace transform of the orbit is bounded by `μ⁻¹ ‖x‖`. -/
theorem norm_integral_laplaceIntegrand_le {μ : ℝ} (hμ : 0 < μ) (x : E) :
    ‖∫ t in Ioi (0 : ℝ), S.laplaceIntegrand μ x t‖ ≤ μ⁻¹ * ‖x‖ := by
  rw [← integral_exp_neg_mul_Ioi_zero hμ, ← integral_mul_const]
  exact norm_integral_le_of_norm_le ((exp_neg_integrableOn_Ioi 0 hμ).mul_const ‖x‖)
    (Eventually.of_forall fun t ↦ S.norm_laplaceIntegrand_le μ x t)

end Integrand

section Resolvent

/-- **The resolvent of the semigroup** at the positive shift `μ`: the Laplace transform of the
orbits, `R_μ x = ∫₀^∞ e^{-μ t} S t x dt`, as a bounded operator. -/
def resolvent (μ : PositiveShift) : E →L[ℝ] E :=
  LinearMap.mkContinuous
    { toFun := fun x ↦ ∫ t in Ioi (0 : ℝ), S.laplaceIntegrand μ x t
      map_add' := fun x y ↦ by
        rw [laplaceIntegrand_add]
        show ∫ t in Ioi (0 : ℝ), (S.laplaceIntegrand μ x t + S.laplaceIntegrand μ y t) = _
        exact integral_add (S.integrableOn_laplaceIntegrand μ.2 x)
          (S.integrableOn_laplaceIntegrand μ.2 y)
      map_smul' := fun c x ↦ by
        rw [laplaceIntegrand_smul, RingHom.id_apply]
        show ∫ t in Ioi (0 : ℝ), c • S.laplaceIntegrand μ x t = _
        exact integral_smul c _ }
    (μ : ℝ)⁻¹ (fun x ↦ S.norm_integral_laplaceIntegrand_le μ.2 x)

omit [CompleteSpace E] in
/-- The resolvent, unfolded as the Laplace transform of the orbit. -/
theorem resolvent_apply (μ : PositiveShift) (x : E) :
    S.resolvent μ x = ∫ t in Ioi (0 : ℝ), S.laplaceIntegrand μ x t :=
  rfl

omit [CompleteSpace E] in
/-- The Hille–Yosida bound `‖R_μ‖ ≤ μ⁻¹`. -/
theorem opNorm_resolvent_le (μ : PositiveShift) : ‖S.resolvent μ‖ ≤ (μ : ℝ)⁻¹ :=
  LinearMap.mkContinuous_norm_le _ (inv_nonneg.mpr μ.2.le) _

/-- The semigroup commutes with its resolvent. -/
theorem operator_resolvent (μ : PositiveShift) (h : NNReal) (x : E) :
    S h (S.resolvent μ x) = S.resolvent μ (S h x) := by
  rw [resolvent_apply, resolvent_apply,
    ← ContinuousLinearMap.integral_comp_comm (S h) (S.integrableOn_laplaceIntegrand μ.2 x)]
  exact setIntegral_congr_fun measurableSet_Ioi fun t _ ↦ S.laplaceIntegrand_operator μ h x t

/-- **The resolvent inverts `μ − L` on the domain**: `R_μ (μ f − L f) = f`. -/
theorem resolvent_smul_sub_generator (μ : PositiveShift) (f : S.generatorDomain) :
    S.resolvent μ ((μ : ℝ) • (f : E) - S.generator f) = f := by
  have hμ : (0 : ℝ) < μ := μ.2
  have hderiv : ∀ t ∈ Ioi (0 : ℝ), HasDerivAt (S.laplaceIntegrand μ f)
      (S.laplaceIntegrand μ (S.generator f) t - (μ : ℝ) • S.laplaceIntegrand μ f t) t := by
    intro t ht
    have hexp : HasDerivAt (fun s : ℝ ↦ Real.exp (-(μ : ℝ) * s))
        (Real.exp (-(μ : ℝ) * t) * (-(μ : ℝ) * 1)) t :=
      ((hasDerivAt_id t).const_mul (-(μ : ℝ))).exp
    refine (hexp.smul (S.hasDerivAt_operator_toNNReal f ht)).congr_deriv ?_
    simp only [laplaceIntegrand_apply, smul_smul]
    module
  have hcont : ContinuousWithinAt (S.laplaceIntegrand μ f) (Ici 0) 0 :=
    (S.continuous_laplaceIntegrand μ f).continuousWithinAt
  have hint1 : IntegrableOn (fun t ↦ S.laplaceIntegrand μ (S.generator f) t) (Ioi 0) :=
    S.integrableOn_laplaceIntegrand hμ _
  have hint2 : IntegrableOn (fun t ↦ (μ : ℝ) • S.laplaceIntegrand μ f t) (Ioi 0) :=
    (S.integrableOn_laplaceIntegrand hμ (f : E)).smul (μ : ℝ)
  have hkey := integral_Ioi_of_hasDerivAt_of_tendsto hcont hderiv (hint1.sub hint2)
    (S.tendsto_laplaceIntegrand_atTop hμ (f : E))
  rw [integral_sub hint1 hint2, integral_smul, zero_sub, laplaceIntegrand_apply, mul_zero,
    Real.exp_zero, one_smul, Real.toNNReal_zero, S.zero_apply] at hkey
  rw [map_sub, map_smul, resolvent_apply, resolvent_apply, ← neg_sub, hkey, neg_neg]

/-- On the domain, the difference quotients of `R_μ f` converge to `R_μ (L f)`. -/
theorem tendsto_differenceQuotient_resolvent_of_mem (μ : PositiveShift) (f : S.generatorDomain) :
    Tendsto (fun t : NNReal ↦ (t : ℝ)⁻¹ • (S t (S.resolvent μ f) - S.resolvent μ f)) (𝓝[>] 0)
      (𝓝 (S.resolvent μ (S.generator f))) := by
  refine (((S.resolvent μ).continuous.tendsto _).comp (S.tendsto_generator' f)).congr
    fun t ↦ ?_
  simp only [Function.comp, map_smul, map_sub, operator_resolvent]

/-- The resolvent maps the domain into the domain. -/
theorem resolvent_mem_generatorDomain_of_mem (μ : PositiveShift) (f : S.generatorDomain) :
    S.resolvent μ f ∈ S.generatorDomain :=
  S.mem_generatorDomain_of_tendsto (S.tendsto_differenceQuotient_resolvent_of_mem μ f)

/-- On the domain, `L (R_μ f) = μ R_μ f − f`. -/
theorem generator_resolvent_of_mem (μ : PositiveShift) (f : S.generatorDomain) :
    S.generator ⟨S.resolvent μ f, S.resolvent_mem_generatorDomain_of_mem μ f⟩ =
      (μ : ℝ) • S.resolvent μ f - f := by
  have h1 : S.generator ⟨S.resolvent μ f, S.resolvent_mem_generatorDomain_of_mem μ f⟩ =
      S.resolvent μ (S.generator f) :=
    S.generator_eq_of_tendsto ⟨S.resolvent μ f, S.resolvent_mem_generatorDomain_of_mem μ f⟩
      (S.tendsto_differenceQuotient_resolvent_of_mem μ f)
  rw [h1]
  have h := S.resolvent_smul_sub_generator μ f
  rw [map_sub, map_smul] at h
  calc S.resolvent μ (S.generator f)
      = (μ : ℝ) • S.resolvent μ f -
          ((μ : ℝ) • S.resolvent μ f - S.resolvent μ (S.generator f)) := by abel
    _ = (μ : ℝ) • S.resolvent μ f - f := by rw [h]

/-- Approximation of `R_μ x` by resolvents of domain vectors, with convergent generators. -/
theorem exists_seq_tendsto_resolvent (μ : PositiveShift) (x : E) :
    ∃ v : ℕ → S.generatorDomain,
      Tendsto (fun n ↦ (v n : E)) atTop (𝓝 (S.resolvent μ x)) ∧
        Tendsto (fun n ↦ S.generator (v n)) atTop (𝓝 ((μ : ℝ) • S.resolvent μ x - x)) := by
  obtain ⟨u, hu_mem, hu⟩ := mem_closure_iff_seq_limit.mp (S.dense_generatorDomain x)
  have hRu : Tendsto (fun n ↦ S.resolvent μ (u n)) atTop (𝓝 (S.resolvent μ x)) :=
    ((S.resolvent μ).continuous.tendsto x).comp hu
  refine ⟨fun n ↦ ⟨S.resolvent μ (u n),
    S.resolvent_mem_generatorDomain_of_mem μ ⟨u n, hu_mem n⟩⟩, hRu, ?_⟩
  have hgen : ∀ n, S.generator ⟨S.resolvent μ (u n),
      S.resolvent_mem_generatorDomain_of_mem μ ⟨u n, hu_mem n⟩⟩ =
        (μ : ℝ) • S.resolvent μ (u n) - u n :=
    fun n ↦ S.generator_resolvent_of_mem μ ⟨u n, hu_mem n⟩
  simp_rw [hgen]
  exact (hRu.const_smul (μ : ℝ)).sub hu

/-- **The resolvent maps into the domain.** -/
theorem resolvent_mem_generatorDomain (μ : PositiveShift) (x : E) :
    S.resolvent μ x ∈ S.generatorDomain := by
  obtain ⟨v, hv, hL⟩ := S.exists_seq_tendsto_resolvent μ x
  exact S.mem_generatorDomain_of_tendsto_generator hv hL

/-- **`μ − L` inverts the resolvent**: `L (R_μ x) = μ R_μ x − x` for every `x`. -/
theorem generator_resolvent (μ : PositiveShift) (x : E) :
    S.generator ⟨S.resolvent μ x, S.resolvent_mem_generatorDomain μ x⟩ =
      (μ : ℝ) • S.resolvent μ x - x := by
  obtain ⟨v, hv, hL⟩ := S.exists_seq_tendsto_resolvent μ x
  exact S.generator_eq_of_tendsto_generator hv hL

/-- The generator of a vector exhibited as a resolvent value. -/
theorem generator_eq_of_resolvent_eq (μ : PositiveShift) {f g : E} (hf : f ∈ S.generatorDomain)
    (h : S.resolvent μ g = f) : S.generator ⟨f, hf⟩ = (μ : ℝ) • f - g := by
  subst h
  exact S.generator_resolvent μ g

/-- **The domain is the range of the resolvent**, at every positive shift. -/
theorem generatorDomain_eq_range_resolvent (μ : PositiveShift) :
    (S.generatorDomain : Set E) = Set.range (S.resolvent μ) := by
  refine Set.Subset.antisymm (fun f hf ↦ ?_) ?_
  · exact ⟨(μ : ℝ) • f - S.generator ⟨f, hf⟩, S.resolvent_smul_sub_generator μ ⟨f, hf⟩⟩
  · rintro _ ⟨y, rfl⟩
    exact S.resolvent_mem_generatorDomain μ y

/-- **The resolvent identity** `R_α − R_β = (β − α) R_α R_β`. -/
theorem resolvent_sub_resolvent (α β : PositiveShift) :
    S.resolvent α - S.resolvent β =
      ((β : ℝ) - (α : ℝ)) • (S.resolvent α).comp (S.resolvent β) := by
  ext y
  have hz : S.resolvent α ((α : ℝ) • S.resolvent β y - ((β : ℝ) • S.resolvent β y - y)) =
      S.resolvent β y := by
    have h := S.resolvent_smul_sub_generator α
      ⟨S.resolvent β y, S.resolvent_mem_generatorDomain β y⟩
    rw [S.generator_resolvent β y] at h
    exact h
  rw [map_sub, map_smul, map_sub, map_smul] at hz
  simp only [ContinuousLinearMap.sub_apply, ContinuousLinearMap.smul_apply,
    ContinuousLinearMap.comp_apply]
  calc S.resolvent α y - S.resolvent β y
      = S.resolvent α y - ((α : ℝ) • S.resolvent α (S.resolvent β y) -
          ((β : ℝ) • S.resolvent α (S.resolvent β y) - S.resolvent α y)) := by rw [hz]
    _ = ((β : ℝ) - (α : ℝ)) • S.resolvent α (S.resolvent β y) := by module

/-- The resolvent has dense range. -/
theorem denseRange_resolvent (μ : PositiveShift) : DenseRange (S.resolvent μ) := by
  show Dense (Set.range (S.resolvent μ))
  rw [← S.generatorDomain_eq_range_resolvent μ]
  exact S.dense_generatorDomain

/-- **The resolvent family of a strongly continuous contraction semigroup is a contractive
resolvent.** -/
def toContractiveResolvent : ContractiveResolvent E where
  operator := S.resolvent
  resolvent_identity := S.resolvent_sub_resolvent
  opNorm_le_inv := S.opNorm_resolvent_le
  denseRange := S.denseRange_resolvent

/-- The operators of the contractive resolvent of `S` are its resolvents. -/
theorem toContractiveResolvent_operator (μ : PositiveShift) :
    S.toContractiveResolvent.operator μ = S.resolvent μ :=
  rfl

end Resolvent

end

end MarkovProcess.Semigroup.StronglyContinuousContractionSemigroup
